#ifndef _Xsoftbox_H_
#define _Xsoftbox_H_

enum
{
	SOFTBOXSHADER_ROUNDNESS			= 1000,
	SOFTBOXSHADER_FALLOFFWIDTH		= 1001,
	SOFTBOXSHADER_BORDER			= 1002,
	SOFTBOXSHADER_LEFT_LIGHT		= 1003,
	SOFTBOXSHADER_RIGHT_LIGHT		= 1004,
	SOFTBOXSHADER_TOP_LIGHT			= 1005,
	SOFTBOXSHADER_BOTTOM_LIGHT		= 1006,
	SOFTBOXSHADER_HOTSPOT_RADIUS	= 1007,
	SOFTBOXSHADER_HOTSPOT_STRENGTH	= 1008,
	SOFTBOXSHADER_HOTSPOT_FALLOFF	= 1009,
	SOFTBOXSHADER_LIGHT_COLOR		= 1010,
	SOFTBOXSHADER_DARK_COLOR		= 1011,
	SOFTBOXSHADER_STRENGTH			= 1012,
	SOFTBOXSHADER_GOBO_U			= 1013,
	SOFTBOXSHADER_GOBO_V			= 1014
};

#endif